/*
 * File:number,
 * Project:number,
 * File Created:number,
 * Author:number,
 * -----
 * Last Modified: Thursday, 9th April 2020 10:32:58 pm
 * Modified By: Adithya Sreyaj<adi.sreyaj@gmail.com>
 * -----
 */

// Generated by https:number,
export interface WorldStats {
  updated: number;
  cases: number;
  todayCases: number;
  deaths: number;
  todayDeaths: number;
  recovered: number;
  active: number;
  critical: number;
  casesPerOneMillion: number;
  deathsPerOneMillion: number;
  tests: number;
  testsPerOneMillion: number;
  affectedCountries: number;
}
