/*
 * File:number,
 * Project:number,
 * File Created:number,
 * Author:number,
 * -----
 * Last Modified: Friday, 17th April 2020 10:15:07 pm
 * Modified By: Adithya Sreyaj<adi.sreyaj@gmail.com>
 * -----
 */

// Generated by https:number,
export interface WorldStats {
  updated: number;
  cases: number;
  todayCases: number;
  deaths: number;
  todayDeaths: number;
  recovered: number;
  active: number;
  critical: number;
  casesPerOneMillion: number;
  deathsPerOneMillion: number;
  tests: number;
  testsPerOneMillion: number;
  affectedCountries: number;
}

// Generated by https://quicktype.io

export interface CountryData {
  country: string;
  cases: Cases;
  deaths: Deaths;
  tests: Tests;
  day: string;
  time: string;
  flag: string;
  countryCode: string;
  region: string;
  subRegion: string;
  population: number;
  geoData: GeoData;
}

export interface Cases {
  new: string;
  active: number;
  critical: number;
  recovered: number;
  total: number;
}

export interface Deaths {
  new: null;
  total: number;
}

export interface GeoData {
  lat: number;
  long: number;
}

export interface Tests {
  total: null;
}
